### ISSUE TITLE
[Chore] Clean up unused dependencies and files

### ISSUE THREAD

**Issue by olivierobert** [skrishnan22/google-scraper#20]
## Issue

The UI application defines many dependenciesin  `package.json`, which does not seem used. 

For instance:

Tailwind seems to be a dependency:

https://github.com/skrishnan22/google-scraper/blob/55c77e1f85ab61491fe977a3d8721851a7b6e16d/ui/package.json#L48

However, Bootstrap seems to be the primary CSS framework:

https://github.com/skrishnan22/google-scraper/blob/main/ui/src/styles.scss#L1

Al component's CSS files seem also redundant:

https://github.com/skrishnan22/google-scraper/blob/main/ui/src/app/components/signup/signup.component.scss

## Expected

Remove all unused code and dependencies to reduce the codebase's complexity.

**Comment by skrishnan22** [comment]
Ah, started with tailwind and then decided to use Bootstrap instead. Missed removing it.
